Lds 2278 alb qui change les targets en maintenance
LeComptoirDesPharmacies/lcdp-deployment-manager pull request #28
Opened 2022-04-20 07:28 UTC by alexandreDuComptoirDesPharmacies

2022-04-20 08:46 UTC, LeComptoirDesPharmacies requested changes

2022-04-20 08:46 UTC, LeComptoirDesPharmacies commented on lcdp_deployment_manager/manage_alb.py
> +def get_target_group_with_type_and_workspace(tg_type, workspace):
On pourrait modifier la fonction `get_target_group_with_type_color_and_workspace` afin que quand elle ne reçoit pas de couleur, elle ne met pas le tag filter color

2022-04-20 08:46 UTC, LeComptoirDesPharmacies commented on setup.py
> +    version='1.1.9',  # Start with a small number and increase it with every change you make
Tu peux laisser à 1.1.8, je te montrerais quand on fait l'upgrade de version

2022-04-20 13:16 UTC, alexandreDuComptoirDesPharmacies commented on setup.py
> +    version='1.1.9',  # Start with a small number and increase it with every change you make
c'est un problème de synchro entre develop et master:
* sur master il y a 1.1.9
* sur develop il y a 1.1.8

2022-04-21 07:28 UTC, GeryDuComptoirDesPharmacies commented
Ok pour moi

2022-04-27 14:27 UTC, merged